### PR TITLE
Added align in index

### PR DESCRIPTION
**Pull request by AJCodee**
Added some changes to index.html file.

### CODE REVIEW

**Review by zakariyahali — APPROVED** [review]
So, I'm just commenting for the sake of you being able to look what it looks like when the person 'reviewing' leaves a comment.

**Review by zakariyahali — COMMENTED** [review]
Seems like you've got the hang of it!

**Comment by AJCodee** [comment]
I think we have.. Thank you!

**Review by zakariyahali — COMMENTED** [review]
.

**Pull request merged**
